spring:
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    content-type: text/html
    enabled: true
    encoding: UTF-8
  profiles:
    active: "prod"

---

spring:
  profiles: dev
app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/poll
    username: postgres
    password: 62851030
    pool-size: 30

---

spring:
  profiles: prod
app:
  datasource:
    jdbc-url: jdbc:postgresql://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    pool-size: 30
server:
  port: 5000